version: "2"
services:

  service-registry:
    image: service-registry
    ports:
      - 8761:8761

  product-price:
    image: product-price
    ports:
      - 8968:8968
    links:
      - service-registry
      - zipkin-dashboard
    depends_on:
      - service-registry
      - zipkin-dashboard

  product-service:
    image: product
    ports:
      - 8956:8956
    links:
      - service-registry
      - zipkin-dashboard
    depends_on:
      - service-registry
      - zipkin-dashboard

  product-detail:
    image: product-detail
    links:
      - service-registry
    ports:
      - 8967:8967
    links:
      - service-registry
      - zipkin-dashboard
    depends_on:
      - service-registry
      - zipkin-dashboard

  zipkin-dashboard:
    image: zipkin-dashboard
    links:
      - service-registry
    ports:
      - 9411:9411
