server:
  port: 8956

eureka:
  instance:
      hostname: localhost
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: product-service
  sleuth:
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false