server:
  port: 8956

eureka:
  instance:
      hostname: service-registry
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://zipkin-dashboard:9411
  sleuth:
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false