server:
  port: 8968
spring:
  application:
    name: product-price
  zipkin:
    base-url: http://zipkin-dashboard:9411

eureka:
  instance:
      hostname: service-registry
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

management:
  security:
    enabled: false
