server:
  port: 8968
spring:
  application:
    name: product-price

eureka:
  instance:
      hostname: localhost
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

management:
  security:
    enabled: false
