server:
  port: 8956

eureka:
  instance:
      hostname: localhost
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: mesures-service
  zipkin:
    enabled: false

management:
  security:
    enabled: false